#### This file consists of data cleaning processes. The final processed data is saved into a csv file which is then utilized for Exploratory Data Analysis.

### IMPORTING LIBRARIES

In [2]:
import pandas as pd
import numpy as np
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
import matplotlib.pyplot as plt
import seaborn as sns

### DATA LOADING

In [3]:
df1 = pd.read_json('/Users/kirtanasridharan/Downloads/Kindle_Store.json', lines=True)
df1

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,4,True,"12 29, 2012",A27UD5HYAKBL97,1423600150,{'Format:': ' Hardcover'},Cheryl,If you like making salsas this is a great book...,Great Book,1356739200,NaN,NaN
1,5,True,"03 6, 2012",A8P5DK8LLOYGH,1423600150,{'Format:': ' Hardcover'},Shay365,great little book. simple and right to the poi...,great little book,1330992000,3,NaN
2,5,True,"08 12, 2009",A3OM9W7DXSUIIY,1423600150,{'Format:': ' Hardcover'},R. Peckham,This book has good pics of the recipes and eas...,very good bok with good ideas.,1250035200,NaN,NaN
3,3,False,"11 3, 2006",A3DPAR2PWB9BT8,1423600150,{'Format:': ' Hardcover'},JJSS,"I admire the SF School of Cooking, but was dis...",Ok cookbook,1162512000,3,NaN
4,5,False,"04 11, 2006",A2ONTBSAX7GIOV,1423600150,{'Format:': ' Hardcover'},Three Guys from Miami,Many people are surprised to find out that we ...,Fresh and Tasty Ideas from Santa Fe!,1144713600,15,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5722983,5,False,"09 2, 2018",A3564F5AHYGXIK,B01HJH82WY,{'Format:': ' Kindle Edition'},Amazon Customer,I purchased this book because I wrote somethin...,Good story teller,1535846400,NaN,[https://images-na.ssl-images-amazon.com/image...
5722984,5,True,"08 13, 2018",A1UX5HUK0QI049,B01HJH82WY,{'Format:': ' Kindle Edition'},Leonard Tillerman,Pride is a funny thing. It can lead people to ...,5 out of 5 Spiritual Stars for this one! *****,1534118400,NaN,NaN
5722985,5,True,"06 22, 2018",A2IHCZ2QVATVMZ,B01HJH82WY,{'Format:': ' Kindle Edition'},Shawn,What a fabulous story about a spiritual journe...,It Glows!,1529625600,NaN,NaN
5722986,5,False,"08 7, 2016",A2FNGRZF97UZ49,B01HJH82WY,{'Format:': ' Kindle Edition'},Regina O&#039;Connell,Wow and wow! Y'all have got to read this book!...,Wow!,1470528000,NaN,NaN
5722987,5,False,"07 30, 2016",A3DSNAWKL6QXHZ,B01HJH82WY,{'Format:': ' Kindle Edition'},Heraclitus,"Unique in too many ways to count, Flint of Dre...",Excellent story-telling,1469836800,NaN,NaN

### DROPPING IRRELEVANT COLUMNS

In [4]:
df1.drop(['vote', 'image'], axis=1, inplace=True)
df1

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime
0,4,True,"12 29, 2012",A27UD5HYAKBL97,1423600150,{'Format:': ' Hardcover'},Cheryl,If you like making salsas this is a great book...,Great Book,1356739200
1,5,True,"03 6, 2012",A8P5DK8LLOYGH,1423600150,{'Format:': ' Hardcover'},Shay365,great little book. simple and right to the poi...,great little book,1330992000
2,5,True,"08 12, 2009",A3OM9W7DXSUIIY,1423600150,{'Format:': ' Hardcover'},R. Peckham,This book has good pics of the recipes and eas...,very good bok with good ideas.,1250035200
3,3,False,"11 3, 2006",A3DPAR2PWB9BT8,1423600150,{'Format:': ' Hardcover'},JJSS,"I admire the SF School of Cooking, but was dis...",Ok cookbook,1162512000
4,5,False,"04 11, 2006",A2ONTBSAX7GIOV,1423600150,{'Format:': ' Hardcover'},Three Guys from Miami,Many people are surprised to find out that we ...,Fresh and Tasty Ideas from Santa Fe!,1144713600
...,...,...,...,...,...,...,...,...,...,...
5722983,5,False,"09 2, 2018",A3564F5AHYGXIK,B01HJH82WY,{'Format:': ' Kindle Edition'},Amazon Customer,I purchased this book because I wrote somethin...,Good story teller,1535846400
5722984,5,True,"08 13, 2018",A1UX5HUK0QI049,B01HJH82WY,{'Format:': ' Kindle Edition'},Leonard Tillerman,Pride is a funny thing. It can lead people to ...,5 out of 5 Spiritual Stars for this one! *****,1534118400
5722985,5,True,"06 22, 2018",A2IHCZ2QVATVMZ,B01HJH82WY,{'Format:': ' Kindle Edition'},Shawn,What a fabulous story about a spiritual journe...,It Glows!,1529625600
5722986,5,False,"08 7, 2016",A2FNGRZF97UZ49,B01HJH82WY,{'Format:': ' Kindle Edition'},Regina O&#039;Connell,Wow and wow! Y'all have got to read this book!...,Wow!,1470528000
5722987,5,False,"07 30, 2016",A3DSNAWKL6QXHZ,B01HJH82WY,{'Format:': ' Kindle Edition'},Heraclitus,"Unique in too many ways to count, Flint of Dre...",Excellent story-telling,1469836800

In [5]:
df1.shape

(5722988, 10)

In [6]:
df1['reviewTime'] = pd.to_datetime(df1['reviewTime'], format='%m %d, %Y')

In [7]:
df1['verified'] = df1['verified'].astype(int)

In [8]:
df1.isnull().sum()

overall                0
verified               0
reviewTime             0
reviewerID             0
asin                   0
style             413434
reviewerName         306
reviewText          1624
summary             3077
unixReviewTime         0
dtype: int64

In [9]:
df1=df1.dropna()

In [10]:
df1.isnull().sum()

overall           0
verified          0
reviewTime        0
reviewerID        0
asin              0
style             0
reviewerName      0
reviewText        0
summary           0
unixReviewTime    0
dtype: int64

In [11]:
df1.shape

(5304855, 10)

In [12]:
df1

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime
0,4,1,2012-12-29,A27UD5HYAKBL97,1423600150,{'Format:': ' Hardcover'},Cheryl,If you like making salsas this is a great book...,Great Book,1356739200
1,5,1,2012-03-06,A8P5DK8LLOYGH,1423600150,{'Format:': ' Hardcover'},Shay365,great little book. simple and right to the poi...,great little book,1330992000
2,5,1,2009-08-12,A3OM9W7DXSUIIY,1423600150,{'Format:': ' Hardcover'},R. Peckham,This book has good pics of the recipes and eas...,very good bok with good ideas.,1250035200
3,3,0,2006-11-03,A3DPAR2PWB9BT8,1423600150,{'Format:': ' Hardcover'},JJSS,"I admire the SF School of Cooking, but was dis...",Ok cookbook,1162512000
4,5,0,2006-04-11,A2ONTBSAX7GIOV,1423600150,{'Format:': ' Hardcover'},Three Guys from Miami,Many people are surprised to find out that we ...,Fresh and Tasty Ideas from Santa Fe!,1144713600
...,...,...,...,...,...,...,...,...,...,...
5722983,5,0,2018-09-02,A3564F5AHYGXIK,B01HJH82WY,{'Format:': ' Kindle Edition'},Amazon Customer,I purchased this book because I wrote somethin...,Good story teller,1535846400
5722984,5,1,2018-08-13,A1UX5HUK0QI049,B01HJH82WY,{'Format:': ' Kindle Edition'},Leonard Tillerman,Pride is a funny thing. It can lead people to ...,5 out of 5 Spiritual Stars for this one! *****,1534118400
5722985,5,1,2018-06-22,A2IHCZ2QVATVMZ,B01HJH82WY,{'Format:': ' Kindle Edition'},Shawn,What a fabulous story about a spiritual journe...,It Glows!,1529625600
5722986,5,0,2016-08-07,A2FNGRZF97UZ49,B01HJH82WY,{'Format:': ' Kindle Edition'},Regina O&#039;Connell,Wow and wow! Y'all have got to read this book!...,Wow!,1470528000
5722987,5,0,2016-07-30,A3DSNAWKL6QXHZ,B01HJH82WY,{'Format:': ' Kindle Edition'},Heraclitus,"Unique in too many ways to count, Flint of Dre...",Excellent story-telling,1469836800

In [14]:
start_date = '2013-01-01'
end_date = '2018-12-31'

filtered_data = df1[(df1['reviewTime'] >= start_date) & (df1['reviewTime'] <= end_date)]
filtered_data

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime
5,5,0,2015-03-01,A2PRJSH8RLRB46,1423600150,{'Format:': ' Hardcover'},William Yarberry,Yum!,Five Stars,1425168000
6,5,1,2015-02-11,A2PP8CPXOFI5I6,1423600150,{'Format:': ' Hardcover'},Larry Occhipinti DVM,Excellent.,Five Stars,1423612800
7,5,1,2015-01-09,A3CWUPYGW55FUE,1423600150,{'Format:': ' Hardcover'},Nell Bryant,Great recipes. I feel like I'm in the great S...,Great recipes. I feel like I'm in the great ...,1420761600
8,5,1,2014-12-19,ABMI85UTQ7WN5,1423600150,{'Format:': ' Hardcover'},Edward A. Rubin,Cannot recommend the salsas in this book stron...,Highly Recommended,1418947200
9,5,1,2014-12-16,A24582E5Z79UT6,1423600150,{'Format:': ' Kindle Edition'},Susan W,For the salsa lover who likes new recipes!!,Five Stars,1418688000
...,...,...,...,...,...,...,...,...,...,...
5722983,5,0,2018-09-02,A3564F5AHYGXIK,B01HJH82WY,{'Format:': ' Kindle Edition'},Amazon Customer,I purchased this book because I wrote somethin...,Good story teller,1535846400
5722984,5,1,2018-08-13,A1UX5HUK0QI049,B01HJH82WY,{'Format:': ' Kindle Edition'},Leonard Tillerman,Pride is a funny thing. It can lead people to ...,5 out of 5 Spiritual Stars for this one! *****,1534118400
5722985,5,1,2018-06-22,A2IHCZ2QVATVMZ,B01HJH82WY,{'Format:': ' Kindle Edition'},Shawn,What a fabulous story about a spiritual journe...,It Glows!,1529625600
5722986,5,0,2016-08-07,A2FNGRZF97UZ49,B01HJH82WY,{'Format:': ' Kindle Edition'},Regina O&#039;Connell,Wow and wow! Y'all have got to read this book!...,Wow!,1470528000
5722987,5,0,2016-07-30,A3DSNAWKL6QXHZ,B01HJH82WY,{'Format:': ' Kindle Edition'},Heraclitus,"Unique in too many ways to count, Flint of Dre...",Excellent story-telling,1469836800

### CONVERTING STYLE COLUMN TO EASY TO USE DATA FORMAT.

In [15]:
filtered_data['style'].head(10)

5          {'Format:': ' Hardcover'}
6          {'Format:': ' Hardcover'}
7          {'Format:': ' Hardcover'}
8          {'Format:': ' Hardcover'}
9     {'Format:': ' Kindle Edition'}
10    {'Format:': ' Kindle Edition'}
11         {'Format:': ' Hardcover'}
12         {'Format:': ' Hardcover'}
13         {'Format:': ' Hardcover'}
14    {'Format:': ' Kindle Edition'}
Name: style, dtype: object

In [16]:
style_df = pd.json_normalize(filtered_data['style'])
style_df

                 Format:
0              Hardcover
1              Hardcover
2              Hardcover
3              Hardcover
4         Kindle Edition
...                  ...
4973166   Kindle Edition
4973167   Kindle Edition
4973168   Kindle Edition
4973169   Kindle Edition
4973170   Kindle Edition

[4973171 rows x 1 columns]

In [17]:
style_df['Format:'].unique()

array([' Hardcover', ' Kindle Edition', ' Mass Market Paperback',
       ' Paperback', ' Audio Cassette', ' 3.5" disk',
       ' Audible Audiobook', ' Audio CD', ' MP3 CD', ' MP3 Music', ' DVD',
       ' Leather Bound', ' Bonded Leather', ' Calendar', ' Comic',
       ' Sheet music', ' Library Binding',
       ' Kindle Edition with Audio/Video', ' School & Library Binding',
       ' Print Magazine', ' Spiral-bound', ' Loose Leaf',
       ' Imitation Leather', ' Unknown Binding', ' Perfect Paperback',
       ' Board book', ' Vinyl', ' CD-ROM', ' Digital', ' Misc. Supplies',
       ' Flexibound', ' Diary', ' Journal', ' VHS Tape', ' Accessory',
       ' Prime Video', ' Blu-ray', ' Plastic Comb', ' Hardcover Comic',
       ' 3.5" and 5.25" disks', ' Single Issue Magazine', ' Pamphlet',
       ' Workbook', ' Hardcover-spiral', ' Cards', ' Toy', ' Pocket Book',
       ' DVD-ROM', ' Print on Demand (Paperback)', ' Health and Beauty',
       ' Tankobon Softcover', ' Printed Access Code', ' Staple Bound',
       ' Album', ' Kitchen'], dtype=object)

In [18]:
style_df.isna().sum()

Format:    0
dtype: int64

In [19]:
filtered_data['Format'] = filtered_data['style'].apply(lambda x: x.get('Format:', '') if isinstance(x, dict) else '')

/var/folders/tj/jsf55sq57fl57fp6z_m3j8_r0000gn/T/ipykernel_30676/3914157556.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['Format'] = filtered_data['style'].apply(lambda x: x.get('Format:', '') if isinstance(x, dict) else '')

In [20]:
filtered_data['Format'].unique()

array([' Hardcover', ' Kindle Edition', ' Mass Market Paperback',
       ' Paperback', ' Audio Cassette', ' 3.5" disk',
       ' Audible Audiobook', ' Audio CD', ' MP3 CD', ' MP3 Music', ' DVD',
       ' Leather Bound', ' Bonded Leather', ' Calendar', ' Comic',
       ' Sheet music', ' Library Binding',
       ' Kindle Edition with Audio/Video', ' School & Library Binding',
       ' Print Magazine', ' Spiral-bound', ' Loose Leaf',
       ' Imitation Leather', ' Unknown Binding', ' Perfect Paperback',
       ' Board book', ' Vinyl', ' CD-ROM', ' Digital', ' Misc. Supplies',
       ' Flexibound', ' Diary', ' Journal', ' VHS Tape', ' Accessory',
       ' Prime Video', ' Blu-ray', ' Plastic Comb', ' Hardcover Comic',
       ' 3.5" and 5.25" disks', ' Single Issue Magazine', ' Pamphlet',
       ' Workbook', ' Hardcover-spiral', ' Cards', ' Toy', ' Pocket Book',
       ' DVD-ROM', ' Print on Demand (Paperback)', ' Health and Beauty',
       ' Tankobon Softcover', ' Printed Access Code', ' Staple Bound',
       ' Album', ' Kitchen'], dtype=object)

In [21]:
filtered_data['format'] = filtered_data['style'].apply(lambda x: x.get('Format:', '') if isinstance(x, dict) else '')

# Use .loc to modify the DataFrame
filtered_data.loc[:, 'format'] = filtered_data['format']

# Drop the original 'style' column if needed
filtered_data.drop('style', axis=1, inplace=True)

/var/folders/tj/jsf55sq57fl57fp6z_m3j8_r0000gn/T/ipykernel_30676/125290925.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['format'] = filtered_data['style'].apply(lambda x: x.get('Format:', '') if isinstance(x, dict) else '')
/var/folders/tj/jsf55sq57fl57fp6z_m3j8_r0000gn/T/ipykernel_30676/125290925.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data.loc[:, 'format'] = filtered_data['format']
/var/folders/tj/jsf55sq57fl57fp6z_m3j8_r0000gn/T/ipykernel_30676/125290925.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data.drop('style', axis=1, inplace=True)

In [22]:
filtered_data.drop(['Format'], axis=1, inplace=True)
filtered_data.head()

/var/folders/tj/jsf55sq57fl57fp6z_m3j8_r0000gn/T/ipykernel_30676/3665431426.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data.drop(['Format'], axis=1, inplace=True)

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,format
5,5,0,2015-03-01,A2PRJSH8RLRB46,1423600150,William Yarberry,Yum!,Five Stars,1425168000,Hardcover
6,5,1,2015-02-11,A2PP8CPXOFI5I6,1423600150,Larry Occhipinti DVM,Excellent.,Five Stars,1423612800,Hardcover
7,5,1,2015-01-09,A3CWUPYGW55FUE,1423600150,Nell Bryant,Great recipes. I feel like I'm in the great S...,Great recipes. I feel like I'm in the great ...,1420761600,Hardcover
8,5,1,2014-12-19,ABMI85UTQ7WN5,1423600150,Edward A. Rubin,Cannot recommend the salsas in this book stron...,Highly Recommended,1418947200,Hardcover
9,5,1,2014-12-16,A24582E5Z79UT6,1423600150,Susan W,For the salsa lover who likes new recipes!!,Five Stars,1418688000,Kindle Edition

### LOADING META DATA OF THE BOOKS REVIEWED CONTAINING INFORMATION LIKE 
### PRODUCT RANK, FEATURE, BRAND, TITLE OF THE BOOK, CATEGORY OF THE BOOK,PRICE AND ASSOCIATED IMAGES

In [23]:
df2 = pd.read_json('/Users/kirtanasridharan/Downloads/meta_Kindle_Store.json', lines=True)
df2

,category,tech1,description,fit,title,also_buy,tech2,brand,feature,rank,also_view,details,main_cat,similar_item,date,price,asin,imageURL,imageURLHighRes
0,"[Kindle Store, Kindle eBooks, Science Fiction ...",,[],,,"[B007NLCJBC, B01FARODH8]",,Arthur K. Barnes,[],"1,716,849 Paid in Kindle Store (","[B000FBF81K, B00PBDMER8]","{'File Size:': '295 KB', 'Print Length:': '113...",Buy a Kindle,,NaT,,B000FA5KKA,[],[]
1,"[Kindle Store, Kindle eBooks, Engineering & Tr...",,[],,,"[B00AYWTHZS, B071CTK28D]",,Visit Amazon's Paul A. Craig Page,[],"1,683,973 Paid in Kindle Store (",[B00AYWTHZS],"{'File Size:': '1648 KB', 'Print Length:': '26...",Buy a Kindle,,NaT,,B000FA5M3K,[],[]
2,"[Kindle Store, Kindle eBooks, Biographies & Me...",,[],,,[],,Jean Marie Stine,[],"3,394,136 Paid in Kindle Store (",[],"{'File Size:': '262 KB', 'Print Length:': '103...",Buy a Kindle,,NaT,,B000FA5KJQ,[],[]
3,"[Kindle Store, Kindle eBooks, Science Fiction ...",,[],,,[],,Arthur K. Barnes,[],"1,884,541 Paid in Kindle Store (",[],"{'File Size:': '251 KB', 'Print Length:': '116...",Buy a Kindle,,NaT,,B000FA5NSO,[],[]
4,"[Kindle Store, Kindle eBooks, Business & Money]",,[],,,"[B000SEGKF2, B004774LR0, B018LE1KUK, B0015DRO7...",,Visit Amazon's Ethan M. Rasiel Page,[],"72,075 Paid in Kindle Store (","[B018LE1KUK, B000SEGKF2, B007XWFZSA, B0015DRO7...","{'File Size:': '953 KB', 'Print Length:': '187...",Buy a Kindle,,NaT,,B000FA5KX2,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491665,"[Kindle Store, Kindle eBooks, Science Fiction ...",,[],,Den of Dark Angels eBook,[],,Visit Amazon's Kenna McKinnon Page,[],"8,671 Free in Kindle Store (","[B07LB2LY17, B07DMZJ29M, B00O3GTJEU, B077XG66X...","{'File Size:': '1918 KB', 'Print Length:': '30...",Buy a Kindle,,NaT,,B01HJDS9W6,[],[]
491666,"[Kindle Store, Kindle eBooks, Literature & Fic...",,[],,Poison Kisses 2: My Best Kept Secret - Kindle ...,"[B01F1X1630, B07C7G3YFN, B07CYV92TH]",,Visit Amazon's Kia Meche' Page,[],"743,760 Paid in Kindle Store (",[B01F1X1630],"{'File Size:': '3159 KB', 'Print Length:': '15...",Buy a Kindle,,NaT,,B01HJENY3Y,[],[]
491667,"[Kindle Store, Kindle eBooks, Religion & Spiri...",,[],,Renewing Your Mind!: Secrets to Having All You...,"[B06VVS5NTN, B01BWYW7DK, B01K7T52JM, B079DTMZR...",,Visit Amazon's MICHAEL ENDWELL Page,[],"573,570 Paid in Kindle Store (","[B06VVS5NTN, B01K9D9EKE, B07HRLXB59, B071HBRKN...","{'File Size:': '658 KB', 'Print Length:': '37 ...",Buy a Kindle,,NaT,,B01HJFVTKS,[],[]
491668,"[Kindle Store, Kindle eBooks, Literature & Fic...",,[],,Restless Daniel No Ordinary Boy: A child&#39;s...,[],,Visit Amazon's Cally Finsbury Page,[],"2,661,876 Paid in Kindle Store (",[],"{'File Size:': '177 KB', 'Print Length:': '47 ...",Buy a Kindle,,NaT,,B01HJH8CDS,[],[]
491669,"[Kindle Store, Kindle eBooks, Literature & Fic...",,[],,Flint of Dreams - Kindle edition,"[B07L8JHQWC, B07H31JY76, B079Q8QM87, B07C2YPQ2...",,Visit Amazon's Charles Peterson Sheppard Page,[],"293,775 Paid in Kindle Store (","[B00DJANLQS, B07M9BH3LS, B00NNNCA7M, B00AGZ27F...","{'File Size:': '761 KB', 'Print Length:': '341...",Buy a Kindle,,NaT,,B01HJH82WY,[],[]

In [24]:
df2.isna().sum()

category                0
tech1                   0
description             0
fit                     0
title                   0
also_buy                0
tech2                   0
brand                   0
feature                 0
rank                    0
also_view               0
details                 0
main_cat                0
similar_item            0
date               491670
price                   0
asin                    0
imageURL                0
imageURLHighRes         0
dtype: int64

In [25]:
df2['rank'].head()

0    1,716,849 Paid in Kindle Store (
1    1,683,973 Paid in Kindle Store (
2    3,394,136 Paid in Kindle Store (
3    1,884,541 Paid in Kindle Store (
4       72,075 Paid in Kindle Store (
Name: rank, dtype: object

In [26]:
df2['product_rank'] = pd.to_numeric(df2['rank'].replace('[^0-9]', '', regex=True), errors='coerce')


df2.head()

,category,tech1,description,fit,title,also_buy,tech2,brand,feature,rank,also_view,details,main_cat,similar_item,date,price,asin,imageURL,imageURLHighRes,product_rank
0,"[Kindle Store, Kindle eBooks, Science Fiction ...",,[],,,"[B007NLCJBC, B01FARODH8]",,Arthur K. Barnes,[],"1,716,849 Paid in Kindle Store (","[B000FBF81K, B00PBDMER8]","{'File Size:': '295 KB', 'Print Length:': '113...",Buy a Kindle,,NaT,,B000FA5KKA,[],[],1716849.0
1,"[Kindle Store, Kindle eBooks, Engineering & Tr...",,[],,,"[B00AYWTHZS, B071CTK28D]",,Visit Amazon's Paul A. Craig Page,[],"1,683,973 Paid in Kindle Store (",[B00AYWTHZS],"{'File Size:': '1648 KB', 'Print Length:': '26...",Buy a Kindle,,NaT,,B000FA5M3K,[],[],1683973.0
2,"[Kindle Store, Kindle eBooks, Biographies & Me...",,[],,,[],,Jean Marie Stine,[],"3,394,136 Paid in Kindle Store (",[],"{'File Size:': '262 KB', 'Print Length:': '103...",Buy a Kindle,,NaT,,B000FA5KJQ,[],[],3394136.0
3,"[Kindle Store, Kindle eBooks, Science Fiction ...",,[],,,[],,Arthur K. Barnes,[],"1,884,541 Paid in Kindle Store (",[],"{'File Size:': '251 KB', 'Print Length:': '116...",Buy a Kindle,,NaT,,B000FA5NSO,[],[],1884541.0
4,"[Kindle Store, Kindle eBooks, Business & Money]",,[],,,"[B000SEGKF2, B004774LR0, B018LE1KUK, B0015DRO7...",,Visit Amazon's Ethan M. Rasiel Page,[],"72,075 Paid in Kindle Store (","[B018LE1KUK, B000SEGKF2, B007XWFZSA, B0015DRO7...","{'File Size:': '953 KB', 'Print Length:': '187...",Buy a Kindle,,NaT,,B000FA5KX2,[],[],72075.0

In [27]:
import re
rank_counts = df2['rank'].str.extract('(Paid in Kindle Store|Free in Kindle Store)', flags=re.IGNORECASE).value_counts()

# Display the counts
print(rank_counts)

Paid in Kindle Store    473749
Free in Kindle Store     14270
dtype: int64

In [28]:
non_matching_ranks = df2[~df2['rank'].str.contains('(Paid in Kindle Store|Free in Kindle Store)', case=False, na=False)]

# Display the values that do not match
print(non_matching_ranks['rank'].value_counts())

/var/folders/tj/jsf55sq57fl57fp6z_m3j8_r0000gn/T/ipykernel_30676/1426704684.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  non_matching_ranks = df2[~df2['rank'].str.contains('(Paid in Kindle Store|Free in Kindle Store)', case=False, na=False)]

[]                                                      3640
259,579 in Kindle Store (                                  1
3,964,719 in Kindle Store (                                1
3,178,043 in Kindle Store (                                1
905,828 in Kindle Store (                                  1
3,353,923 in Kindle Store (                                1
1 Hottest New Young Adult Humor Release                    1
1,001,487 in Kindle Store (                                1
1,364 Free in Kindle as well as in these categories.       1
3,721,556 in Kindle Store (                                1
1 Hottest New Satire Humor Release                         1
x22; for &                                                 1
Name: rank, dtype: int64

In [29]:
values_to_remove = ['1 Hottest New Young Adult Humor Release', '1 Hottest New Satire Humor Release', 'x22; for &']
df2 = df2[~df2['rank'].isin(values_to_remove)]

In [30]:
df2['details'][0]

{'File Size:': '295 KB',
 'Print Length:': '113 pages',
 'Publisher:': 'FuturesPast Editions (October 14, 2001)',
 'Publication Date:': 'October 14, 2001',
 'Language:': 'English',
 'ASIN:': 'B000FA5KKA',
 'Word Wise:': 'Enabled',
 'Lending:': 'Enabled'}

In [31]:
from pandas import json_normalize
details_df = json_normalize(df2['details'])


details_df.isnull().sum()

File Size:                      1046
Print Length:                   9336
Publisher:                    187851
Publication Date:               1447
Language:                        110
ASIN:                              0
Word Wise:                      1395
Lending:                        1395
Page Numbers Source ISBN:     445866
Simultaneous Device Usage:    252152
ISBN-10:                      490322
ISBN-13:                      490319
Release Date:                 491308
dtype: int64

In [32]:
details_df['book_length(pages)'] = pd.to_numeric(details_df['Print Length:'].replace('[^0-9]', '', regex=True), errors='coerce')
details_df

,File Size:,Print Length:,Publisher:,Publication Date:,Language:,ASIN:,Word Wise:,Lending:,Page Numbers Source ISBN:,Simultaneous Device Usage:,ISBN-10:,ISBN-13:,Release Date:,book_length(pages)
0,295 KB,113 pages,"FuturesPast Editions (October 14, 2001)","October 14, 2001",English,B000FA5KKA,Enabled,Enabled,NaN,NaN,NaN,NaN,NaN,113.0
1,1648 KB,268 pages,"McGraw-Hill Education; 1 edition (December 31,...","December 31, 1999",English,B000FA5M3K,Not Enabled,Not Enabled,0071348441,"Up to 4 simultaneous devices, per publisher li...",NaN,NaN,NaN,268.0
2,262 KB,103 pages,"PageTurner (October 14, 2001)","October 14, 2001",English,B000FA5KJQ,Enabled,Enabled,NaN,NaN,NaN,NaN,NaN,103.0
3,251 KB,116 pages,"PageTurner (March 15, 2002)","March 15, 2002",English,B000FA5NSO,Not Enabled,Enabled,NaN,NaN,NaN,NaN,NaN,116.0
4,953 KB,187 pages,"McGraw-Hill Education; 1 edition (February 22,...","February 22, 1999",English,B000FA5KX2,Enabled,Not Enabled,NaN,"Up to 4 simultaneous devices, per publisher li...",NaN,NaN,NaN,187.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491662,1918 KB,304 pages,"Creativia; 1 edition (June 24, 2016)","June 24, 2016",English,B01HJDS9W6,Enabled,Enabled,1534936440,Unlimited,NaN,NaN,NaN,304.0
491663,3159 KB,154 pages,"Tiece Mickens Presents, LLC (June 24, 2016)","June 24, 2016",English,B01HJENY3Y,Enabled,Enabled,NaN,Unlimited,NaN,NaN,NaN,154.0
491664,658 KB,37 pages,"ENDWELL BUSINESS CONSULT (June 24, 2016)","June 24, 2016",English,B01HJFVTKS,Enabled,Not Enabled,NaN,NaN,NaN,NaN,NaN,37.0
491665,177 KB,47 pages,NaN,"June 24, 2016",English,B01HJH8CDS,Enabled,Enabled,NaN,NaN,NaN,NaN,NaN,47.0
491666,761 KB,341 pages,"Charles Peterson Sheppard; 1 edition (June 24,...","June 24, 2016",English,B01HJH82WY,Enabled,Enabled,NaN,NaN,NaN,NaN,NaN,341.0

In [33]:
details_df['language'] = details_df['Language:'].fillna('Unknown')

In [34]:
details_df['book_length(pages)'] = details_df['book_length(pages)'].fillna(0)

In [35]:
details_df = details_df.rename(columns={'ASIN:': 'asin'})

In [36]:
columns_to_keep = ['book_length(pages)', 'language', 'asin']

# Keep only the desired columns
details_df = details_df[columns_to_keep]
details_df

        book_length(pages) language        asin
0                    113.0  English  B000FA5KKA
1                    268.0  English  B000FA5M3K
2                    103.0  English  B000FA5KJQ
3                    116.0  English  B000FA5NSO
4                    187.0  English  B000FA5KX2
...                    ...      ...         ...
491662               304.0  English  B01HJDS9W6
491663               154.0  English  B01HJENY3Y
491664                37.0  English  B01HJFVTKS
491665                47.0  English  B01HJH8CDS
491666               341.0  English  B01HJH82WY

[491667 rows x 3 columns]

In [37]:
details_df.isnull().sum()

book_length(pages)    0
language              0
asin                  0
dtype: int64

In [38]:
df2.drop(['similar_item', 'date', 'price', 'imageURL', 'imageURLHighRes', 'also_buy', 
          'tech1', 'tech2', 'feature','description', 'fit', 'also_view', 'main_cat', 'rank'], axis=1, inplace=True)
df2

/var/folders/tj/jsf55sq57fl57fp6z_m3j8_r0000gn/T/ipykernel_30676/1478610831.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(['similar_item', 'date', 'price', 'imageURL', 'imageURLHighRes', 'also_buy',

,category,title,brand,details,asin,product_rank
0,"[Kindle Store, Kindle eBooks, Science Fiction ...",,Arthur K. Barnes,"{'File Size:': '295 KB', 'Print Length:': '113...",B000FA5KKA,1716849.0
1,"[Kindle Store, Kindle eBooks, Engineering & Tr...",,Visit Amazon's Paul A. Craig Page,"{'File Size:': '1648 KB', 'Print Length:': '26...",B000FA5M3K,1683973.0
2,"[Kindle Store, Kindle eBooks, Biographies & Me...",,Jean Marie Stine,"{'File Size:': '262 KB', 'Print Length:': '103...",B000FA5KJQ,3394136.0
3,"[Kindle Store, Kindle eBooks, Science Fiction ...",,Arthur K. Barnes,"{'File Size:': '251 KB', 'Print Length:': '116...",B000FA5NSO,1884541.0
4,"[Kindle Store, Kindle eBooks, Business & Money]",,Visit Amazon's Ethan M. Rasiel Page,"{'File Size:': '953 KB', 'Print Length:': '187...",B000FA5KX2,72075.0
...,...,...,...,...,...,...
491665,"[Kindle Store, Kindle eBooks, Science Fiction ...",Den of Dark Angels eBook,Visit Amazon's Kenna McKinnon Page,"{'File Size:': '1918 KB', 'Print Length:': '30...",B01HJDS9W6,8671.0
491666,"[Kindle Store, Kindle eBooks, Literature & Fic...",Poison Kisses 2: My Best Kept Secret - Kindle ...,Visit Amazon's Kia Meche' Page,"{'File Size:': '3159 KB', 'Print Length:': '15...",B01HJENY3Y,743760.0
491667,"[Kindle Store, Kindle eBooks, Religion & Spiri...",Renewing Your Mind!: Secrets to Having All You...,Visit Amazon's MICHAEL ENDWELL Page,"{'File Size:': '658 KB', 'Print Length:': '37 ...",B01HJFVTKS,573570.0
491668,"[Kindle Store, Kindle eBooks, Literature & Fic...",Restless Daniel No Ordinary Boy: A child&#39;s...,Visit Amazon's Cally Finsbury Page,"{'File Size:': '177 KB', 'Print Length:': '47 ...",B01HJH8CDS,2661876.0
491669,"[Kindle Store, Kindle eBooks, Literature & Fic...",Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,"{'File Size:': '761 KB', 'Print Length:': '341...",B01HJH82WY,293775.0

In [39]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 491667 entries, 0 to 491669
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   category      491667 non-null  object
 1   title         491667 non-null  object
 2   brand         491667 non-null  object
 3   details       491667 non-null  object
 4   asin          491667 non-null  object
 5   product_rank  488027 non-null  float64
dtypes: float64(1), object(5)
memory usage: 42.4+ MB

In [40]:
df2 = pd.merge(df2, details_df, on='asin', how='left')
df2

,category,title,brand,details,asin,product_rank,book_length(pages),language
0,"[Kindle Store, Kindle eBooks, Science Fiction ...",,Arthur K. Barnes,"{'File Size:': '295 KB', 'Print Length:': '113...",B000FA5KKA,1716849.0,113.0,English
1,"[Kindle Store, Kindle eBooks, Engineering & Tr...",,Visit Amazon's Paul A. Craig Page,"{'File Size:': '1648 KB', 'Print Length:': '26...",B000FA5M3K,1683973.0,268.0,English
2,"[Kindle Store, Kindle eBooks, Biographies & Me...",,Jean Marie Stine,"{'File Size:': '262 KB', 'Print Length:': '103...",B000FA5KJQ,3394136.0,103.0,English
3,"[Kindle Store, Kindle eBooks, Science Fiction ...",,Arthur K. Barnes,"{'File Size:': '251 KB', 'Print Length:': '116...",B000FA5NSO,1884541.0,116.0,English
4,"[Kindle Store, Kindle eBooks, Business & Money]",,Visit Amazon's Ethan M. Rasiel Page,"{'File Size:': '953 KB', 'Print Length:': '187...",B000FA5KX2,72075.0,187.0,English
...,...,...,...,...,...,...,...,...
491662,"[Kindle Store, Kindle eBooks, Science Fiction ...",Den of Dark Angels eBook,Visit Amazon's Kenna McKinnon Page,"{'File Size:': '1918 KB', 'Print Length:': '30...",B01HJDS9W6,8671.0,304.0,English
491663,"[Kindle Store, Kindle eBooks, Literature & Fic...",Poison Kisses 2: My Best Kept Secret - Kindle ...,Visit Amazon's Kia Meche' Page,"{'File Size:': '3159 KB', 'Print Length:': '15...",B01HJENY3Y,743760.0,154.0,English
491664,"[Kindle Store, Kindle eBooks, Religion & Spiri...",Renewing Your Mind!: Secrets to Having All You...,Visit Amazon's MICHAEL ENDWELL Page,"{'File Size:': '658 KB', 'Print Length:': '37 ...",B01HJFVTKS,573570.0,37.0,English
491665,"[Kindle Store, Kindle eBooks, Literature & Fic...",Restless Daniel No Ordinary Boy: A child&#39;s...,Visit Amazon's Cally Finsbury Page,"{'File Size:': '177 KB', 'Print Length:': '47 ...",B01HJH8CDS,2661876.0,47.0,English
491666,"[Kindle Store, Kindle eBooks, Literature & Fic...",Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,"{'File Size:': '761 KB', 'Print Length:': '341...",B01HJH82WY,293775.0,341.0,English

In [41]:
filtered_data = pd.merge(filtered_data, df2, on='asin', how='left')
filtered_data

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,format,category,title,brand,details,product_rank,book_length(pages),language
0,5,0,2015-03-01,A2PRJSH8RLRB46,1423600150,William Yarberry,Yum!,Five Stars,1425168000,Hardcover,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,1,2015-02-11,A2PP8CPXOFI5I6,1423600150,Larry Occhipinti DVM,Excellent.,Five Stars,1423612800,Hardcover,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,1,2015-01-09,A3CWUPYGW55FUE,1423600150,Nell Bryant,Great recipes. I feel like I'm in the great S...,Great recipes. I feel like I'm in the great ...,1420761600,Hardcover,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,1,2014-12-19,ABMI85UTQ7WN5,1423600150,Edward A. Rubin,Cannot recommend the salsas in this book stron...,Highly Recommended,1418947200,Hardcover,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,2014-12-16,A24582E5Z79UT6,1423600150,Susan W,For the salsa lover who likes new recipes!!,Five Stars,1418688000,Kindle Edition,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4973166,5,0,2018-09-02,A3564F5AHYGXIK,B01HJH82WY,Amazon Customer,I purchased this book because I wrote somethin...,Good story teller,1535846400,Kindle Edition,"[Kindle Store, Kindle eBooks, Literature & Fic...",Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,"{'File Size:': '761 KB', 'Print Length:': '341...",293775.0,341.0,English
4973167,5,1,2018-08-13,A1UX5HUK0QI049,B01HJH82WY,Leonard Tillerman,Pride is a funny thing. It can lead people to ...,5 out of 5 Spiritual Stars for this one! *****,1534118400,Kindle Edition,"[Kindle Store, Kindle eBooks, Literature & Fic...",Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,"{'File Size:': '761 KB', 'Print Length:': '341...",293775.0,341.0,English
4973168,5,1,2018-06-22,A2IHCZ2QVATVMZ,B01HJH82WY,Shawn,What a fabulous story about a spiritual journe...,It Glows!,1529625600,Kindle Edition,"[Kindle Store, Kindle eBooks, Literature & Fic...",Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,"{'File Size:': '761 KB', 'Print Length:': '341...",293775.0,341.0,English
4973169,5,0,2016-08-07,A2FNGRZF97UZ49,B01HJH82WY,Regina O&#039;Connell,Wow and wow! Y'all have got to read this book!...,Wow!,1470528000,Kindle Edition,"[Kindle Store, Kindle eBooks, Literature & Fic...",Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,"{'File Size:': '761 KB', 'Print Length:': '341...",293775.0,341.0,English
4973170,5,0,2016-07-30,A3DSNAWKL6QXHZ,B01HJH82WY,Heraclitus,"Unique in too many ways to count, Flint of Dre...",Excellent story-telling,1469836800,Kindle Edition,"[Kindle Store, Kindle eBooks, Literature & Fic...",Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,"{'File Size:': '761 KB', 'Print Length:': '341...",293775.0,341.0,English

In [42]:
filtered_data.drop(['details'], axis=1, inplace=True)
filtered_data.columns

Index(['overall', 'verified', 'reviewTime', 'reviewerID', 'asin',
       'reviewerName', 'reviewText', 'summary', 'unixReviewTime', 'format',
       'category', 'title', 'brand', 'product_rank', 'book_length(pages)',
       'language'],
      dtype='object')

In [130]:
df2.drop(['asin'], axis=1, inplace=True)

In [43]:
# Assuming 'filtered_data' and 'df2' are your DataFrames
common_asin_values = filtered_data['asin'][filtered_data['asin'].isin(df2['asin'])].unique()

print("Unique asin values present in both filtered_data and df2:")
print(common_asin_values)
print("\nNumber of unique asin values :", len(common_asin_values))

Unique asin values present in both filtered_data and df2:
['B000FA5KK0' 'B000FA64QO' 'B000FA5PV4' ... 'B01HJDS9W6' 'B01HJH8CDS'
 'B01HJH82WY']

Number of unique asin values : 386165

In [167]:
filtered_data['asin'].nunique()

387690

In [45]:
filtered_data_common_asin = filtered_data[filtered_data['asin'].isin(df2['asin'])]
filtered_data_common_asin.shape

(4953191, 16)

In [46]:
filtered_data.shape

(4973171, 16)

In [48]:
filtered_data_common_asin['category']

10         [Kindle Store, Kindle eBooks, Literature & Fic...
11         [Kindle Store, Kindle eBooks, Literature & Fic...
12         [Kindle Store, Kindle eBooks, Literature & Fic...
13         [Kindle Store, Kindle eBooks, Literature & Fic...
14         [Kindle Store, Kindle eBooks, Literature & Fic...
                                 ...
4973166    [Kindle Store, Kindle eBooks, Literature & Fic...
4973167    [Kindle Store, Kindle eBooks, Literature & Fic...
4973168    [Kindle Store, Kindle eBooks, Literature & Fic...
4973169    [Kindle Store, Kindle eBooks, Literature & Fic...
4973170    [Kindle Store, Kindle eBooks, Literature & Fic...
Name: category, Length: 4953191, dtype: object

In [49]:
filtered_data_common_asin['category'] = filtered_data_common_asin['category'].apply(
    lambda category_list: [category for category in category_list if 'Kindle Store' not in category and 'Kindle eBooks' not in category]
)

/var/folders/tj/jsf55sq57fl57fp6z_m3j8_r0000gn/T/ipykernel_30676/383950080.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data_common_asin['category'] = filtered_data_common_asin['category'].apply(

In [50]:
from bs4 import BeautifulSoup
# Remove HTML tags and filter out empty elements
filtered_data_common_asin['category'] = filtered_data_common_asin['category'].apply(
    lambda category_list: [BeautifulSoup(category, 'html.parser').get_text() for category in category_list if category]
)

/var/folders/tj/jsf55sq57fl57fp6z_m3j8_r0000gn/T/ipykernel_30676/2365056050.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data_common_asin['category'] = filtered_data_common_asin['category'].apply(

In [55]:
filtered_data_common_asin['category'] = filtered_data_common_asin['category'].apply(lambda x: [item for item in x if item != ''])

/var/folders/tj/jsf55sq57fl57fp6z_m3j8_r0000gn/T/ipykernel_30676/3857883995.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data_common_asin['category'] = filtered_data_common_asin['category'].apply(lambda x: [item for item in x if item != ''])

In [56]:
filtered_data_common_asin['category'].head(10)

10    [Literature & Fiction]
11    [Literature & Fiction]
12    [Literature & Fiction]
13    [Literature & Fiction]
14    [Literature & Fiction]
15    [Literature & Fiction]
16    [Literature & Fiction]
17    [Literature & Fiction]
18    [Literature & Fiction]
19    [Literature & Fiction]
Name: category, dtype: object

In [59]:
filtered_data_common_asin.head()

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,format,category,title,brand,product_rank,book_length(pages),language
10,3,1,2014-10-11,A36PGTGIU6TWY2,B000FA5KK0,Timothy Isaacson,"Enjoyed the read. A bit of a twist to it, fun ...",western with a twist.,1412985600,Kindle Edition,[Literature & Fiction],,Visit Amazon's Max Brand Page,5062792.0,247.0,English
11,5,1,2014-10-05,A176WT5VCAX69W,B000FA5KK0,George,I have enjoyed all work by this author,Five Stars,1412467200,Kindle Edition,[Literature & Fiction],,Visit Amazon's Max Brand Page,5062792.0,247.0,English
12,4,1,2014-07-03,A2LSKD2H9U8N0J,B000FA5KK0,sandra sue marsolek,"pretty good story, a little exaggerated, but I...",pretty good story,1404345600,Kindle Edition,[Literature & Fiction],,Visit Amazon's Max Brand Page,5062792.0,247.0,English
13,5,1,2014-05-26,A2QP13XTJND1QS,B000FA5KK0,Tpl,"If you've read other max brand westerns, you k...",A very good book,1401062400,Kindle Edition,[Literature & Fiction],,Visit Amazon's Max Brand Page,5062792.0,247.0,English
14,5,1,2014-02-18,A1B26H4XPQ1FKP,B000FA5KK0,Wayne Harrill,I had missed reading this rare treasure thank ...,Surprise,1392681600,Kindle Edition,[Literature & Fiction],,Visit Amazon's Max Brand Page,5062792.0,247.0,English

In [60]:
filtered_data_common_asin['language'].value_counts()

English            4866102
Spanish              69472
German                5099
French                4318
Portuguese            2356
Italian               2199
Afrikaans             1531
Chinese                475
Russian                423
Japanese               421
Dutch                  400
Catalan                 64
Unknown                 56
Swedish                 52
Norwegian               43
Irish                   41
Danish                  37
Hindi                   31
Finnish                 21
Icelandic               12
Romansh                 11
Tamil                    9
Bokml Norwegian          5
Castilian                4
Multilingual             3
Galician                 3
Welsh                    2
Provenal                 1
Name: language, dtype: int64

In [76]:
language_counts = {
    'English': 4866102,
    'Spanish': 69472,
    'German': 5099,
    'French': 4318,
    'Portuguese': 2356,
    'Italian': 2199,
    'Afrikaans': 1531,
    'Chinese': 475,
    'Russian': 423,
    'Japanese': 421,
    'Dutch': 400,
    'Catalan': 64,
    'Unknown': 56,
    'Swedish': 52,
    'Norwegian': 43,
    'Irish': 41,
    'Danish': 37,
    'Hindi': 31,
    'Finnish': 21,
    'Icelandic': 12,
    'Romansh': 11,
    'Tamil': 9,
    'Bokml Norwegian': 5,
    'Castilian': 4,
    'Multilingual': 3,
    'Galician': 3,
    'Welsh': 2,
    'Provenal': 1
}

selected_reviews = pd.DataFrame()

max_reviews_to_sample = 5000 

for language, count in language_counts.items():
    # Calculate 80% of the total occurrences for each language
    print('Language:', language)
    if language in ['English', 'Spanish']:
        num_rows_to_select = np.random.randint(1000,min(count, max_reviews_to_sample))
        print('num_rows_to_select', num_rows_to_select)
    else:
        # For other languages, sample up to 80% of the occurrences
        eighty_percent = int(0.8 * count)
        num_rows_to_select = 1 if eighty_percent < 1 else np.random.randint(1, min(count, eighty_percent) + 1)
        print('num_rows_to_select', num_rows_to_select)

    # Select random rows for the current language
    language_reviews = filtered_data_common_asin[filtered_data_common_asin['language'] == language].sample(n=num_rows_to_select, random_state=42)
    
    selected_reviews = pd.concat([selected_reviews, language_reviews])

Language: English
num_rows_to_select 2248
Language: Spanish
num_rows_to_select 2597
Language: German
num_rows_to_select 3501
Language: French
num_rows_to_select 1219
Language: Portuguese
num_rows_to_select 1060
Language: Italian
num_rows_to_select 557
Language: Afrikaans
num_rows_to_select 913
Language: Chinese
num_rows_to_select 238
Language: Russian
num_rows_to_select 68
Language: Japanese
num_rows_to_select 223
Language: Dutch
num_rows_to_select 305
Language: Catalan
num_rows_to_select 31
Language: Unknown
num_rows_to_select 25
Language: Swedish
num_rows_to_select 15
Language: Norwegian
num_rows_to_select 4
Language: Irish
num_rows_to_select 27
Language: Danish
num_rows_to_select 8
Language: Hindi
num_rows_to_select 3
Language: Finnish
num_rows_to_select 12
Language: Icelandic
num_rows_to_select 9
Language: Romansh
num_rows_to_select 4
Language: Tamil
num_rows_to_select 4
Language: Bokml Norwegian
num_rows_to_select 1
Language: Castilian
num_rows_to_select 2
Language: Multilingual
num_rows_to_select 2
Language: Galician
num_rows_to_select 2
Language: Welsh
num_rows_to_select 1
Language: Provenal
num_rows_to_select 1

In [77]:
selected_reviews.shape

(13080, 16)

In [78]:
# Saving cleaned data to device to be used later
selected_reviews.to_csv('/Users/kirtanasridharan/Downloads/cleaned.csv', index=False)

In [79]:
filtered_data_common_asin.to_csv('/Users/kirtanasridharan/Downloads/filtered_kindle.csv', index=False)

In [80]:
filtered_data_common_asin

,overall,verified,reviewTime,reviewerID,asin,reviewerName,reviewText,summary,unixReviewTime,format,category,title,brand,product_rank,book_length(pages),language
10,3,1,2014-10-11,A36PGTGIU6TWY2,B000FA5KK0,Timothy Isaacson,"Enjoyed the read. A bit of a twist to it, fun ...",western with a twist.,1412985600,Kindle Edition,[Literature & Fiction],,Visit Amazon's Max Brand Page,5062792.0,247.0,English
11,5,1,2014-10-05,A176WT5VCAX69W,B000FA5KK0,George,I have enjoyed all work by this author,Five Stars,1412467200,Kindle Edition,[Literature & Fiction],,Visit Amazon's Max Brand Page,5062792.0,247.0,English
12,4,1,2014-07-03,A2LSKD2H9U8N0J,B000FA5KK0,sandra sue marsolek,"pretty good story, a little exaggerated, but I...",pretty good story,1404345600,Kindle Edition,[Literature & Fiction],,Visit Amazon's Max Brand Page,5062792.0,247.0,English
13,5,1,2014-05-26,A2QP13XTJND1QS,B000FA5KK0,Tpl,"If you've read other max brand westerns, you k...",A very good book,1401062400,Kindle Edition,[Literature & Fiction],,Visit Amazon's Max Brand Page,5062792.0,247.0,English
14,5,1,2014-02-18,A1B26H4XPQ1FKP,B000FA5KK0,Wayne Harrill,I had missed reading this rare treasure thank ...,Surprise,1392681600,Kindle Edition,[Literature & Fiction],,Visit Amazon's Max Brand Page,5062792.0,247.0,English
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4973166,5,0,2018-09-02,A3564F5AHYGXIK,B01HJH82WY,Amazon Customer,I purchased this book because I wrote somethin...,Good story teller,1535846400,Kindle Edition,[Literature & Fiction],Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,293775.0,341.0,English
4973167,5,1,2018-08-13,A1UX5HUK0QI049,B01HJH82WY,Leonard Tillerman,Pride is a funny thing. It can lead people to ...,5 out of 5 Spiritual Stars for this one! *****,1534118400,Kindle Edition,[Literature & Fiction],Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,293775.0,341.0,English
4973168,5,1,2018-06-22,A2IHCZ2QVATVMZ,B01HJH82WY,Shawn,What a fabulous story about a spiritual journe...,It Glows!,1529625600,Kindle Edition,[Literature & Fiction],Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,293775.0,341.0,English
4973169,5,0,2016-08-07,A2FNGRZF97UZ49,B01HJH82WY,Regina O&#039;Connell,Wow and wow! Y'all have got to read this book!...,Wow!,1470528000,Kindle Edition,[Literature & Fiction],Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,293775.0,341.0,English
4973170,5,0,2016-07-30,A3DSNAWKL6QXHZ,B01HJH82WY,Heraclitus,"Unique in too many ways to count, Flint of Dre...",Excellent story-telling,1469836800,Kindle Edition,[Literature & Fiction],Flint of Dreams - Kindle edition,Visit Amazon's Charles Peterson Sheppard Page,293775.0,341.0,English